server:
  port: ${PORT}
spring:
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      #username: ${DB_USER}
      #password: ${DB_PASS}
      database: ${DB_NAME}
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    consumer:
      group-id: sparks-service
    topics:
      user:
        create: create-user-topic
        find-all: find-all-users-topic
        find-by-id: find-user-by-id-topic
        update-by-id: update-user-by-id-topic
        delete-by-id: delete-user-by-id-topic
      product:
        create: create-product-topic
        find-all: find-all-products-topic
        find-by-id: find-product-by-id-topic
        update-by-id: update-product-by-id-topic
        delete-by-id: delete-product-by-id-topic
    reply-topics:
      user:
        create: create-user-reply-topic
        find-all: find-all-users-reply-topic
        find-by-id: find-user-by-id-reply-topic
        update-by-id: update-user-by-id-reply-topic
        delete-by-id: delete-user-by-id-reply-topic
      product:
        create: create-product-reply-topic
        find-all: find-all-products-reply-topic
        find-by-id: find-product-by-id-reply-topic
        update-by-id: update-product-by-id-reply-topic
        delete-by-id: delete-product-by-id-reply-topic